version: '3'
services:
  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - 1990:80
    volumes:
      - ./www/laravel:/var/www:cached
    container_name: nginx

  php:
    build:
      context: ./phpfpm
    volumes:
      - ./www/laravel/pictureShare:/var/www:cached
    depends_on:
      - mysql
    container_name: pictureShare

  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=pictureShare
      - MYSQL_ROOT_PASSWORD=secret
    ports:
        - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    container_name: pictureShare_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8888:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
